title: jpvillaisaza.com
author: Juan Pedro Villa Isaza

email: 584947+jpvillaisaza@users.noreply.github.com

social:
  bluesky: https://bsky.app/profile/jpvillaisaza.com
  github: https://github.com/jpvillaisaza
  instagram: https://www.instagram.com/jpvillaisaza

collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

include:
  - _pages

exclude:
  - README.md

permalink: pretty
timezone: America/Bogota

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post

plugins:
  - jekyll-redirect-from
