- platform: GitHub
  url: https://github.com/jpvillaisaza

- platform: Instagram
  url: https://www.instagram.com/jpvillaisaza/

- platform: LinkedIn
  url: https://www.linkedin.com/in/jpvillaisaza/

- platform: Mastodon
  url: https://mastodon.social/@jpvillaisaza
